### ISSUE TITLE
Add a Google search form for the forum

### ISSUE THREAD

**Issue by BPLRFE** [solvespace/solvespace-web#6]
Adding a note on the forum page saying:

You can search the forum using Google.
Typing
compile site:solvespace.com
in the search box in Google will search the Homepage and the forum for "compile".

Looking at lines 4/5 in the makefile, i am missing the entry for the forum page.
Is it created seperately ?

**Comment by whitequark** [comment]
Even better, an embedded search form. But this is something only @jwesthues can do, currently.

> Looking at lines 4/5 in the makefile, i am missing the entry for the forum page.
> Is it created seperately ?

Yes, I don't have any control over the forum.

**Comment by jwesthues** [comment]
I've added a Google Custom Search Engine, same as the LDmicro forum. I should probably replace those with the Bing version or something, out of loyalty and since the ads are pretty intrusive; but let me know if you see any problems in the meantime.

The forum is entangled with some other sites. I need to separate that and get it checked in too.

**Comment by BPLRFE** [comment]
At the moment that does the job very good.
Thanks for investing the time ...
